//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarketingCourseEntities1 : DbContext
    {
        public MarketingCourseEntities1()
            : base("name=MarketingCourseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
    }
}
